// Run-result layer of the wcdraft data contract.
//
// A `RunResult` is the persistent record of one complete play-through. It is:
//   - SUFFICIENT for leaderboard verification (carries all three version
//     anchors + the scenario_id so the server can re-derive),
//   - SUFFICIENT for the post-match UI (carries `record`, `aggregate`, the
//     full `score_breakdown`, the per-player report cards, and a narrative
//     payload pointer), and
//   - DERIVED end-to-end from (DraftState, RunScenario, seed, version anchors)
//     such that an identical input MUST produce a byte-identical RunResult.
//
// SELF-CONTAINMENT INVARIANT: `computeScore(run, cfg)` MUST be computable from
// `RunResult` and `ScoringConfig` ALONE — never from raw `MatchResult[]`. To
// honor that, the per-round goals-for / goals-against and clean-sheet counts
// the scoring engine needs are PERSISTED on the run: see `round_results` and
// `aggregate.clean_sheets`.

import type { MatchRound } from "./primitives.js";
import type { ScoreComponent } from "./scoring.js";
import type { PlayerRunStats } from "./stats.js";

/**
 * Per-match summary persisted on `RunResult` so scoring can read the
 * round-progression multiplier from the same persisted run that carries
 * `score` / `score_breakdown` / `player_stats`.
 *
 * Source mapping (from each `MatchResult` on the user's path):
 *   - round         ← MatchResult.round
 *   - advanced      ← MatchResult.advanced (true iff this match advanced
 *                      the user into the next round)
 *   - outcome       ← MatchResult.outcome (knockout never 'D')
 *   - goals_for     ← user_goals + (user_goals_et ?? 0), shootout EXCLUDED
 *   - goals_against ← opp_goals  + (opp_goals_et  ?? 0), shootout EXCLUDED
 *
 * `round_results` is ordered by tournament path (group 1..3 then knockout
 * ladder). A user eliminated before the final has fewer than 8 entries.
 */
export interface RoundResult {
  round: MatchRound;
  advanced: boolean;
  outcome: "W" | "D" | "L";
  goals_for: number;
  goals_against: number;
}

/**
 * Persisted result of one complete tournament run.
 *
 * `undefeated_regulation` is FALSE if ANY knockout match required a shootout
 * to resolve — shootout wins still count as run wins (`shootout_wins` /
 * `counts_as_run_win`), but the "undefeated in regulation" bonus is forfeit.
 *
 * `narrative` is a pointer payload — the template id and the filled prose are
 * stored, but the prose is generated by the narrative engine and not
 * authoritative; the authoritative narrative facts are derivable on demand
 * via `deriveNarrativeFacts`. The persisted `narrative.narrative_seed` MUST
 * equal `deriveSubseed(seed, "narrative")` and the schema refinement enforces
 * this (so a leaderboard submission cannot smuggle a tampered seed).
 */
export interface RunResult {
  run_id: string;
  scenario_id: string;

  // ─── REPLAY / LEADERBOARD ANCHORS ──────────────────────────────────────────
  // ALL THREE are required to validate a leaderboard submission server-side.
  /** ETL dataset version. */
  dataset_version: string;
  /** Rating-engine version. */
  rating_version: string;
  /** Single core-package semver covering RNG / sim / scoring / ruleset / narrative. */
  engine_version: string;
  /**
   * Master run seed (STRING; never numeric) — the parent seed every substream
   * (match_sim / event_gen / opponent_selection / narrative) is derived from
   * via `deriveSubseed`. Persisted on the run so a server can replay the run
   * end-to-end and re-derive every sub-seed deterministically.
   */
  seed: string;
  // ───────────────────────────────────────────────────────────────────────────

  /** Final round reached (advanced into). */
  reached_round: MatchRound;
  /** Match in which the user was eliminated; null iff `is_champion === true`. */
  eliminated_in_match_id: string | null;
  /** True iff the user XI lifted the trophy. */
  is_champion: boolean;
  /**
   * False if ANY knockout match required a shootout. Forfeits the undefeated
   * bonus even though the shootout itself was won.
   */
  undefeated_regulation: boolean;

  /** Display-formatted record e.g. "8-0", "5-2-1". */
  record: string;
  wins: number;
  draws: number;
  losses: number;
  shootout_wins: number;
  shootout_losses: number;

  /**
   * Per-match summaries in tournament-path order. The atomic source for
   * `computeScore`'s round-progression multipliers and clean-sheet counts;
   * shootout kicks are NEVER reflected in goals_for / goals_against here.
   */
  round_results: RoundResult[];

  aggregate: {
    goals_for: number;
    goals_against: number;
    /**
     * Count of matches with `round_results[i].goals_against === 0`.
     * Persisted so `computeScore` can apply `clean_sheet_bonus` without
     * reading raw `MatchResult[]`.
     */
    clean_sheets: number;
    /**
     * Run top scorer — derived from `MatchEvent` variants via
     * `resolveTopScorer` (eligibility: side==='user' && type ∈ {goal,
     * pen_scored}; tiebreak: goals desc → minutes asc → player_id asc).
     * Null when nobody scored a counting goal.
     */
    top_scorer_player_id: string | null;
  };

  /** Final leaderboard points (sum over `score_breakdown[i].points`). */
  score: number;
  /** Transparent line-by-line breakdown of how `score` was assembled. */
  score_breakdown: ScoreComponent[];

  /** Per-player report card across the run. */
  player_stats: PlayerRunStats[];

  /**
   * Narrative payload pointer. `template_id` identifies which narrative
   * template was selected; `narrative_seed` is the persisted sub-seed used
   * for template selection (must equal `deriveSubseed(seed, "narrative")`);
   * `filled_text` is the rendered prose. The authoritative narrative facts
   * are derivable on demand via `deriveNarrativeFacts(run, matches)`.
   */
  narrative: {
    template_id: string;
    narrative_seed: string;
    filled_text: string;
  };
}
