// Run-result layer of the wcdraft data contract.
//
// A `RunResult` is the persistent record of one complete play-through. It is:
//   - SUFFICIENT for leaderboard verification (carries all three version
//     anchors + the scenario_id so the server can re-derive),
//   - SUFFICIENT for the post-match UI (carries `record`, `aggregate`, the
//     full `score_breakdown`, the per-player report cards, and a narrative
//     payload pointer), and
//   - DERIVED end-to-end from (DraftState, RunScenario, seed, version anchors)
//     such that an identical input MUST produce a byte-identical RunResult.

import type { MatchRound } from "./primitives.js";
import type { ScoreComponent } from "./scoring.js";
import type { PlayerRunStats } from "./stats.js";

/**
 * Persisted result of one complete tournament run.
 *
 * `undefeated_regulation` is FALSE if ANY knockout match required a shootout
 * to resolve — shootout wins still count as run wins (`shootout_wins` /
 * `counts_as_run_win`), but the "undefeated in regulation" bonus is forfeit.
 *
 * `narrative` is a pointer payload — the template id and the filled prose are
 * stored, but the prose is generated by the narrative engine and not
 * authoritative; the authoritative narrative facts are derivable on demand
 * via `deriveNarrativeFacts`.
 */
export interface RunResult {
  run_id: string;
  scenario_id: string;

  // ─── REPLAY / LEADERBOARD ANCHORS ──────────────────────────────────────────
  // ALL THREE are required to validate a leaderboard submission server-side.
  /** ETL dataset version. */
  dataset_version: string;
  /** Rating-engine version. */
  rating_version: string;
  /** Single core-package semver covering RNG / sim / scoring / ruleset / narrative. */
  engine_version: string;
  // ───────────────────────────────────────────────────────────────────────────

  /** Final round reached (advanced into). */
  reached_round: MatchRound;
  /** Match in which the user was eliminated; null iff `is_champion === true`. */
  eliminated_in_match_id: string | null;
  /** True iff the user XI lifted the trophy. */
  is_champion: boolean;
  /**
   * False if ANY knockout match required a shootout. Forfeits the undefeated
   * bonus even though the shootout itself was won.
   */
  undefeated_regulation: boolean;

  /** Display-formatted record e.g. "8-0", "5-2-1". */
  record: string;
  wins: number;
  draws: number;
  losses: number;
  shootout_wins: number;
  shootout_losses: number;

  aggregate: {
    goals_for: number;
    goals_against: number;
    /**
     * Run top scorer — derived from MatchEvent.counts_for_top_scorer via
     * `resolveTopScorer`. Null when nobody scored a counting goal.
     */
    top_scorer_player_id: string | null;
  };

  /** Final leaderboard points (sum over `score_breakdown[i].points`). */
  score: number;
  /** Transparent line-by-line breakdown of how `score` was assembled. */
  score_breakdown: ScoreComponent[];

  /** Per-player report card across the run. */
  player_stats: PlayerRunStats[];

  /**
   * Narrative payload pointer. `template_id` identifies which narrative
   * template was selected; `filled_text` is the rendered prose. The
   * authoritative narrative facts are derivable on demand via
   * `deriveNarrativeFacts(run, matches)`.
   */
  narrative: {
    template_id: string;
    filled_text: string;
  };
}
