import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "How wcdraft handles your data: what we collect, how it is used, cookies, third-party infrastructure, and your rights under GDPR and CCPA.",
};

export default function PrivacyPage() {
  return (
    <div className="container container--narrow page">
      <header className="page-head">
        <span className="eyebrow">Legal</span>
        <h1 className="display">Privacy Policy</h1>
        <p className="page-head__note">Effective date: TBD — pending legal review.</p>
        <p className="lede">
          This draft describes how wcdraft (&ldquo;we&rdquo;, &ldquo;us&rdquo;) collects, uses, and
          protects information when you use the wcdraft website and game. It reflects our intended
          technical stack and will be finalised before launch.
        </p>
      </header>

      <div className="prose">
        <h2>Information we collect</h2>
        <p>
          We aim to collect the minimum needed to run the game. Depending on how you use wcdraft:
        </p>
        <ul>
          <li>
            <strong>Account information.</strong> If you create an account, we store an identifier
            and basic credentials needed for authentication (for example, an email address or a
            third-party sign-in identifier).
          </li>
          <li>
            <strong>Gameplay data.</strong> Drafts you build, runs you complete, scores, and
            leaderboard placements.
          </li>
          <li>
            <strong>Purchase records.</strong> If you buy the one-time ad-free upgrade, our payment
            processor handles your card details; we retain only a record that the purchase was made.
          </li>
          <li>
            <strong>Technical data.</strong> Standard server and request logs (such as IP address,
            browser type, and timestamps) generated by our hosting provider.
          </li>
        </ul>
        <p>
          We do not knowingly collect special-category personal data, and the game does not require
          it.
        </p>

        <h2>How we use information</h2>
        <ul>
          <li>To operate the game — running drafts, scoring runs, and maintaining leaderboards.</li>
          <li>To authenticate you and keep your account secure.</li>
          <li>To process the optional one-time ad-free purchase.</li>
          <li>To serve advertising to players who have not purchased the ad-free upgrade.</li>
          <li>To diagnose problems, prevent abuse, and improve the game.</li>
        </ul>

        <h2>Cookies and similar technologies</h2>
        <p>
          We use cookies and similar technologies that are necessary for the site to function, such
          as keeping you signed in and remembering essential preferences. If and when advertising is
          enabled, our advertising partner may set additional cookies; where required by law, these
          will only be set after you consent. You can control cookies through your browser settings,
          though disabling essential cookies may break parts of the game.
        </p>

        <h2>Third-party infrastructure</h2>
        <p>
          wcdraft relies on a small number of trusted providers. Each processes data only as needed
          to deliver its service, and each maintains its own privacy policy:
        </p>
        <ul>
          <li>
            <strong>Vercel</strong> — website and application hosting, including request and server
            logs.
          </li>
          <li>
            <strong>Neon (PostgreSQL) with Drizzle</strong> — our database for accounts,
            authentication, and gameplay data.
          </li>
          <li>
            <strong>Stripe</strong> — payment processing for the one-time ad-free purchase. Stripe
            receives the payment details necessary to complete your transaction.
          </li>
          <li>
            <strong>Google AdSense</strong> (planned) — advertising for players on the free tier.
            When enabled, Google may process data to serve and measure ads.
          </li>
        </ul>
        <p>
          We do not sell your personal information. We share data with these providers only to run
          the service, or where required by law.
        </p>

        <h2>Your rights (GDPR)</h2>
        <p>
          If you are in the European Economic Area or the United Kingdom, you have the right to
          access, correct, delete, or export your personal data, to restrict or object to certain
          processing, and to withdraw consent at any time. We process personal data on the legal
          bases of performing our contract with you (running the game), your consent (for example,
          advertising cookies), and our legitimate interests (security and abuse prevention). You
          also have the right to lodge a complaint with your local supervisory authority.
        </p>

        <h2>Your rights (CCPA)</h2>
        <p>
          If you are a California resident, you have the right to know what personal information we
          collect and how it is used, to request deletion of your personal information, and to not
          be discriminated against for exercising your rights. We do not sell personal information
          as defined by the CCPA. To exercise these rights, contact us using the details below.
        </p>

        <h2>Children under 13</h2>
        <p>
          wcdraft is not directed to children under 13, and we do not knowingly collect personal
          information from them. If you believe a child under 13 has provided us with personal
          information, please contact us and we will delete it.
        </p>

        <h2>Consent</h2>
        <p>
          By using wcdraft, you agree to this Privacy Policy. Where the law requires consent — for
          example, for non-essential advertising cookies — we will ask for it separately, and you
          may withdraw it at any time without affecting your ability to play the core game.
        </p>

        <h2>Contact</h2>
        <p>
          Questions about this policy or your data? Reach us via the{" "}
          <Link href="/contact">contact page</Link>. This document will be reviewed by counsel and
          dated before the game launches.
        </p>
      </div>
    </div>
  );
}
